spring:
  profiles:
    active: ${profiles.active}
  application:
    name: msb-dongbao-portal-web
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  auto-dialect:
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: msb-mall #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**

# shopping cart config
cart:
  storage:
    redis:
      enabled: true
    mongo:
      enabled: false

# es
# 配置集群名
elasticsearch:
  clusterName: P8
  # 配置节点信息
  clusterNodes:
    - ip: 127.0.0.1
      port: 9300
